In [1]:
2+3+9

14

In [2]:
kanto = [73,67,43]
weights= [0.3, 0.2, 0.5]
# zip gives us pairs made from the corresponding elements of the parameters.
for item in zip(kanto,weights):
    print(item)


(73, 0.3)
(67, 0.2)
(43, 0.5)


In [3]:
# to get the pairs not in a tuple but in separate variables we use two variables.
for x,y in zip(kanto, weights):
    print(x)
    print(y)

73
0.3
67
0.2
43
0.5


In [4]:
import numpy as np

In [5]:
kanto = np.array([73,67,43])

In [6]:
weights = np.array([0.3,0.2,0.5])

In [7]:
type(kanto)

numpy.ndarray

In [8]:
np.dot(kanto, weights)

56.8

In [9]:
%%time
kanto = [73,67,43]
weights= [0.3, 0.2, 0.5]
# zip gives us pairs made from the corresponding elements of the parameters.
for item in zip(kanto,weights):
    print(item)



(73, 0.3)
(67, 0.2)
(43, 0.5)
CPU times: total: 0 ns
Wall time: 0 ns


In [10]:
# 2d array
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [11]:
climate_data.shape

(5, 3)

In [12]:
# 3d array
arr3 = np.array([
    [[7,8,9],
     [10,11,12]],
    [[13,14,15],
     [16,17,18]]])

In [13]:
arr3.shape

(2, 2, 3)

In [14]:
arr1 = np.array([1,"star",3])

In [15]:
arr1.dtype
# dtype('<U11') - a string datatype.

dtype('<U11')

In [16]:
import urllib.request
urllib.request.urlretrieve('https://query.data.world/s/7fvonctqfoovuopbax6vhmrbsvo5fj?dws=00000','globaltemperature.csv')

('globaltemperature.csv', <http.client.HTTPMessage at 0x1e9f92e95d0>)

In [17]:
generic_food = np.genfromtxt('globaltemperature.csv',delimiter = ',', skip_header = 1)

In [18]:
generic_food

array([[   nan,  3.034,  3.574, ...,    nan,    nan,    nan],
       [   nan,  3.083,  3.702, ...,    nan,    nan,    nan],
       [   nan,  5.626,  3.076, ...,    nan,    nan,    nan],
       ...,
       [   nan, 10.801,  0.102, ...,  0.115, 16.29 ,  0.062],
       [   nan,  7.433,  0.119, ...,  0.106, 15.252,  0.063],
       [   nan,  5.518,  0.1  , ...,  0.099, 14.774,  0.062]])

In [19]:
generic_food.shape

(3192, 9)

In [20]:
import os
print(os.getcwd())

C:\Users\pande


In [21]:
# axis =1 -> will add a coloumn  and axis = 0  -> will add a row with concatenate method.

In [22]:
arr2 = np.array([[1,2,3,1],
        [4,5,6,2],
        [7,8,9,3]])

In [23]:
arr3 = np.array([[11,12,13,14],
                 [15,16,17,18],
                 [19,20,21,22]])

In [24]:
arr2+arr3

array([[12, 14, 16, 15],
       [19, 21, 23, 20],
       [26, 28, 30, 25]])

In [25]:
# adding a scalar
arr2 + 3

array([[ 4,  5,  6,  4],
       [ 7,  8,  9,  5],
       [10, 11, 12,  6]])

In [26]:
arr3 = np.array([
                [[1,2,3,4],
                 [5,6,7,8]],
                [[9,10,11,12],
                 [13,14,15,16]],
                [[17,18,19,20],
                 [21,22,23,24]]])

In [27]:
arr3.shape

(3, 2, 4)

In [28]:
# single element
arr3[1,1,2]

15

In [29]:
# subarray using ranges
arr3[1:]

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [30]:
arr3[1:,0:1]

array([[[ 9, 10, 11, 12]],

       [[17, 18, 19, 20]]])

In [31]:
arr3[1:,0:1,:2]

array([[[ 9, 10]],

       [[17, 18]]])

In [32]:
arr3[1,1]

array([13, 14, 15, 16])

In [33]:
# mixing indices and ranges
arr3[1:,1,3]

array([16, 24])

In [34]:
arr3[1:,1,:3]

array([[13, 14, 15],
       [21, 22, 23]])

In [35]:
# other ways of creating numpy arrays
# all zeroes
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
# all ones
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# random vector
np.random.rand(5)

array([0.09643938, 0.79353455, 0.18408451, 0.11415272, 0.33550858])

In [39]:
# random matrix
np.random.randn(2,3)

array([[ 0.49308799, -2.30559743, -1.03359398],
       [-0.44518148,  1.3011888 ,  1.00965089]])

In [40]:
# array with fixed values - ((dimensions), fixed value)
np.full((2,3),56)

array([[56, 56, 56],
       [56, 56, 56]])

In [41]:
# range with start, end and step; won't include "end" number.
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [42]:
np.arange(10,90,3).shape

(27,)

In [43]:
np.arange(10,90,3).reshape(3,3,3) # dimensions should be compatible with array size.

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [44]:
# equally spaced numbers in a range
# start, end, no.of elements in array; "start" and "end" numbers, will be included.
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [45]:
# numpy questions-
import numpy as np

In [46]:
print(np.__version__)

1.26.0


In [47]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker

In [48]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
# reverse a vector
z = np.arange(1,50)
z= z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1]


In [50]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
nz = np.nonzero([1,0,4,6,0,7,8,0,9,0])
print(nz) 

(array([0, 2, 3, 5, 6, 8], dtype=int64),)


In [52]:
import os

In [53]:
# get current working directory
os.getcwd()

'C:\\Users\\pande'

In [54]:
# relative path; "." refers to the current directory
# files with '.' in the beginning are hidden files
# returns a list
os.listdir('.')

['.bash_history',
 '.cache',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.vscode',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'data',
 'Documents',
 'Downloads',
 'Favorites',
 'GitTutorials',
 'globaltemperature.csv',
 'IntelGraphicsProfiles',
 'italy-covid-daywise.csv',
 'Links',
 'Local Settings',
 'moving car',
 'moving cars',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TM.blf',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'numpy.ipynb',
 'OneDrive',
 'pandas.ipynb',
 'PrintHood',
 'PycharmProjects',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'Videos']

In [55]:
# absolute path
os.listdir('C:\\Users\\pande')

['.bash_history',
 '.cache',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.vscode',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'data',
 'Documents',
 'Downloads',
 'Favorites',
 'GitTutorials',
 'globaltemperature.csv',
 'IntelGraphicsProfiles',
 'italy-covid-daywise.csv',
 'Links',
 'Local Settings',
 'moving car',
 'moving cars',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TM.blf',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'numpy.ipynb',
 'OneDrive',
 'pandas.ipynb',
 'PrintHood',
 'PycharmProjects',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'Videos']

In [56]:
os.listdir('C:\\Users\\pande\\Documents')

['My Music', 'My Pictures', 'My Videos']

In [57]:
os.makedirs('.\\data',exist_ok=True)

In [58]:
'data' in os.listdir('.')

True

In [59]:
os.listdir('.\\data')

['dataset1.csv', 'dataset2.csv']

In [60]:
url1 = 'https://query.data.world/s/zyzmxirsumvhst3okx3ikhuc6dmkv7?dws=00000'
url2 = 'https://query.data.world/s/tnwqa7j665s2lszruuip2jtkfvsqhk?dws=00000'

In [61]:
import urllib.request

In [62]:
urllib.request.urlretrieve(url1,'.\\data\\dataset1.csv')

('.\\data\\dataset1.csv', <http.client.HTTPMessage at 0x1e9f980e7d0>)

In [63]:
urllib.request.urlretrieve(url2,'.\\data\\dataset2.csv')

('.\\data\\dataset2.csv', <http.client.HTTPMessage at 0x1e9f986e5d0>)

In [64]:
 os.listdir('.\\data')

['dataset1.csv', 'dataset2.csv']

In [65]:
# open('path', mode=' ') - returns a file object or a file pointer.
# 'b' - binary mode - it is for a file that cannot be read as text - images.
file1 = open('.\\data\\dataset1.csv', mode= 'r')

In [66]:
file1_contents = file1.read()
# file1_contents - is a string.

In [67]:
# when you open a file that file is put into the system RAM.
file1.close()

In [68]:
with open('.\\data\\dataset2.csv','r') as file2:
    file2_contents = file2.read()

In [69]:
with open('.\\data\\dataset2.csv','r') as file2:
    file2_contents = file2.readlines()

In [70]:
file1 = open('.\\data\\dataset1.csv', mode= 'r')
file1_contents = file1.readlines()

In [71]:
def parse_header(header_line):
    return header_line.strip().split(',')

In [72]:
headers = parse_header(file1_contents[0])

In [73]:
headers

['FOOD NAME', 'SCIENTIFIC NAME', 'GROUP', 'SUB GROUP']

In [74]:
def parse_values(data_line):
    values = []
    for item in data_line.strip().split(','):
        if type(item)!= str:
            values.append(float(item))
        elif item == '':
            values.append(0.0)
        else:
            values.append(item)
    return values

In [75]:
parse_values(file1_contents[1])

['Angelica', 'Angelica keiskei', 'Herbs and Spices', 'Herbs']

In [76]:
def create_item_dict(values,header):
    result = {}
    for value,header in zip(values, header):
        result[header] = value
    return result

In [77]:
def read_csv(path):
    result = []
    # open the file in read mode
    with open(path,'r') as f:
        # get a list of lines
        lines = f.readlines()
        # parse the header
        headers = parse_header(lines[0])
        # loop over the remaining lines
        for data_line in lines[1:]:
            # parse the values
            values = parse_values(data_line)
            # create a dicyionary using values and headers
            item_dict = create_item_dict(values,headers)
            # add the dictionary item to the list
            result.append(item_dict)
    return result

In [78]:
# read_csv('.\\data\\dataset2.csv')